version: "3.8"

services:
    mysqldb:
        build:
            context: ./
            dockerfile: mysql.dockerfile
        platform: linux/x86_64
        container_name: healthapi-mysql
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    app:
        depends_on:
            mysqldb:
                condition: service_healthy
        build:
            context: ./
            dockerfile: node.dockerfile
        working_dir: /usr/src/healthapi
        container_name: healthapi-api
        env_file: ./.env
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        volumes:
            - ./controller:/usr/src/healthapi/controller
            - ./routes:/usr/src/healthapi/routes
